version: '3.8'

services:
  cultbot:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: expired-soda-cult-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    restart: unless-stopped
